env:
  - CGO_ENABLED=0
  - PROJECT=github.com/http-everything/httpe
before:
  hooks:
    - go mod tidy
builds:
  - id: httpe
    binary: httpe
    ldflags:
      - "-X {{.Env.PROJECT}}/pkg/version.HTTPEServerVersion={{.Version}}"
      - "-X {{.Env.PROJECT}}/pkg/version.HTTPEServerGitRef={{.Branch}}"
      - "-X {{.Env.PROJECT}}/pkg/version.HTTPEServerCommitID={{.ShortCommit}}"
      - "-X {{.Env.PROJECT}}/pkg/version.HTTPEServerBuildTime={{.CommitTimestamp}}"
      - "-s -w"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
archives:
  - id: httpe
    name_template: >-
      httpe_{{ .Version }}_{{ .Os|title }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}l{{ end }}
    files:
      - example.rules.yaml
      - example.httpe.conf
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ incpatch .Version }}-devel'
changelog:
  sort: asc
release:
  github:
    owner: http-everything
    name: httpe
  draft: false
  prerelease: "true"
