baseURL = 'https://httpe.io/'
languageCode = 'en-us'
title = 'HTTP Everything'

[params]
    [params.docs]
        sidebarIcons = true
        # The theme appears to have a bug. 'false' means prism is enabled.
        prism = false

    [params.social]
        github = "http-everyting/httpe"

    [params.footer]
        copyright = "© :YEAR: Thorsten Kramm. Built in Cologne with ❤️, [Golang](https://go.dev/), and [Hugo](https://gohugo.io/)"

[module]
    [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
    disable = false
    [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false


[markup.goldmark.renderer]
unsafe = true


[menu]
    [[menu.primary]]
        name  = "Documentation"
        url = "docs/"
        identifier = "docs"
        weight = 10