name: Build and deploy docs
on:
  push:
    branches:
      - main
      - docs
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  docs:
    name: Build and deploy docs
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build with Hugo
        run: |
          pwd
          curl -sL https://github.com/gohugoio/hugo/releases/download/v0.123.1/hugo_extended_0.123.1_linux-amd64.tar.gz|tar xzf - hugo
          sudo mv hugo /usr/local/bin/hugo
          hugo version||true
          git tag|tail -n1 > docs/layouts/shortcodes/httpe-version.html
          cd docs
          test -e public||mkdir public
          hugo --minify
          find public

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4