name: Test HTTPE on Linux
on: [push]
jobs:
  test:
    name: Test HTTPE on Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: CPU Info
        run: cat /proc/cpuinfo

      - name: Test
        run: go test -race -v ./...
